IgedEncuesta/Controllers/EncuestaController.cs
using AdministracionInstrumentos;
using iTextSharp.text;
using iTextSharp.text.pdf;
using log4net;
using log4net.Config;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace IgedEncuesta.Controllers
{
    public class EncuestaController : Controller
    {

        private static readonly ILog log = LogManager.GetLogger("Web");
        List<PdfReader> memoriaReaderes = new List<PdfReader>();
        public EncuestaController()
        {
            XmlConfigurator.Configure();
        }

        ~EncuestaController()
        {

        }

        private string Usuario = string.Empty;
        private string codigoEncuesta = string.Empty;
        public ActionResult Encuesta(string codigoHogar = null, string tipo = null)
        {
            try
            {
                Encuesta objSesion = new Encuesta();
                string userIdApp;
                userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();
                gic_Tema tema = new gic_Tema();
                List<gic_Tema> temas = null;

                var perfiles = objSesion.getValorCampoSesion("PERFILES", userIdApp);
                temas = tema.getTemasxInstrumento(1, 1, perfiles);
                var serializedData = Newtonsoft.Json.JsonConvert.SerializeObject(temas);
                objSesion.guardarCampoSesion(int.Parse(userIdApp), "TEMAS", serializedData);
                List<gic_Tema> temasValidar = null;

                /************************************************************************
                PARA QUE NO VALIDE LA SESION , 
                *************************************************************************/
                if (codigoHogar == null)
                    codigoHogar = objSesion.getValorCampoSesion("CODHOGAR", userIdApp);
                else
                    objSesion.guardarCampoSesion(int.Parse(userIdApp), "CODHOGAR", codigoHogar);
                
                codigoEncuesta = codigoHogar;
                temasValidar = tema.getTemasValidados(codigoEncuesta);
                
                var serializeTemas = Newtonsoft.Json.JsonConvert.SerializeObject(temasValidar);
                objSesion.guardarCampoSesion(int.Parse(userIdApp), "TEMASVALIDAR", serializeTemas);
                int terminoCap = tema.get_VerficarCapitulosPrimeros(codigoEncuesta);
                
                objSesion.guardarCampoSesion(int.Parse(userIdApp), "CAPTERMI", terminoCap.ToString());
                //adicion para  guardar los valores en una cookie
                return View(temas);
            }
            catch (Exception e)
            {
                log.Error("EncuestaController / Encuesta , Error: " + e.Message.ToString());
                return null;
            }
        }

        //[ExpiraSesionFilter]
        public ActionResult cargarTema(string idTema)
        {

            try
            {

                Encuesta objSesion = new Encuesta();
                string userIdApp;
                userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();
                List<gic_Tema> temas = new List<gic_Tema>();
                gic_Tema tema = new gic_Tema();
                var objeto = objSesion.getValorCampoSesion("TEMAS", userIdApp);
                temas = Newtonsoft.Json.JsonConvert.DeserializeObject<List<gic_Tema>>(objeto);
                tema = temas.FirstOrDefault(x => x.tem_IdTema == int.Parse(idTema));
                var serializeTema = Newtonsoft.Json.JsonConvert.SerializeObject(tema);
                objSesion.guardarCampoSesion(int.Parse(userIdApp), "TEMA", serializeTema);
                int preguntaInicial = 1;
                objSesion.guardarCampoSesion(int.Parse(userIdApp), "PREGUNTAINICIAL", preguntaInicial.ToString());
                objSesion.guardarCampoSesion(int.Parse(userIdApp), "IDTEMA", idTema.ToString());
                string codigoEncuesta = objSesion.getValorCampoSesion("CODHOGAR", userIdApp);
                int idInstrumento = int.Parse(System.Configuration.ConfigurationManager.AppSettings["IdInstrumento"].ToString());
                gic_PreguntaRespuestasFlujo preguntasRespuestasFlujo = new gic_PreguntaRespuestasFlujo();
                preguntasRespuestasFlujo = PreguntaMostrar(codigoEncuesta, int.Parse(idTema), idInstrumento, preguntaInicial, "TEM");
                preguntasRespuestasFlujo.temaAmostrar = tema;
                return PartialView("_CargaEncuesta", preguntasRespuestasFlujo);
            }
            catch (Exception e)
            {
                log.Error("EncuestaController / cargarTema , Error: " + e.Message.ToString());
                return null;
            }

        }


        //Traer pregunta siguiente
        private gic_PreguntaRespuestasFlujo PreguntaMostrar(string codHogar, int idTema, int idInstrumento, int idPregunta, string flujo)
        {
            try
            {

                gic_PreguntaRespuestasFlujo preguntasRespuestasFlujo = new gic_PreguntaRespuestasFlujo();
                gic_Pregunta pregunta = new gic_Pregunta();
                gic_Tema tema = new gic_Tema();
                gic_Hogar hogar = new gic_Hogar();
                gic_ElementosPadre padreYorden = new gic_ElementosPadre();
                List<gic_PreguntasxPersona> colleccionPreguntas = new List<gic_PreguntasxPersona>();
                List<gic_RespuestaxEncuesta> coleccionRespuestas = new List<gic_RespuestaxEncuesta>();
                gic_RespuestaxEncuesta respuestaXencuesta = new gic_RespuestaxEncuesta();
                gic_PreguntasxPersona preguntaXpersonaGen = new gic_PreguntasxPersona();
                gic_RespuestaxEncuesta respuestaPreguntaGen = new gic_RespuestaxEncuesta();
                DataTable departamentos = new DataTable();
                List<SelectListItem> SelectDepartamentos = new List<SelectListItem>();
                List<gic_RespuestaNuevo> opcionesRespuestas = new List<gic_RespuestaNuevo>();
                gic_RespuestaNuevo objRespuestas = new gic_RespuestaNuevo();
                List<gic_RespuestaNuevo> opcionesRespuestasFiltrado = new List<gic_RespuestaNuevo>();
                DataTable municipios = new DataTable();
                DataTable direccionterritoriales = new DataTable();
                DataTable puntosatencion = new DataTable();
                DataTable municipiosatencion = new DataTable();
                List<SelectListItem> SelectMunicipios = new List<SelectListItem>();
                List<SelectListItem> SelecDireccionesTerritoriales = new List<SelectListItem>();
                List<SelectListItem> SelecPuntosDeAtencion = new List<SelectListItem>();
                List<SelectListItem> SelecMunicipioAtencion = new List<SelectListItem>();

                var watch = System.Diagnostics.Stopwatch.StartNew();
                int idPersonaEncuestada = hogar.get_IdPersonaEncuestada(codHogar);
                watch.Stop();
                var elapsedMs = watch.ElapsedMilliseconds;
                log.Info("metodo get_IdPersonaEncuestada , tiempoDuracion: " + elapsedMs);
                watch = System.Diagnostics.Stopwatch.StartNew();
                padreYorden = pregunta.getMaxPreguntaPadre(codHogar, idTema);
                watch.Stop();
                elapsedMs = watch.ElapsedMilliseconds;
                log.Info("metodo getMaxPreguntaPadre , tiempoDuracion: " + elapsedMs);
                List<string> listaAutoCompletar = new List<string>();
                HttpCookie reqCookies = Request.Cookies["SesionIged"];
                string usuario = reqCookies["USUARIO"].ToString();
                
                preguntasRespuestasFlujo.flujo = flujo;
                preguntasRespuestasFlujo.idPersonaEncuesta = idPersonaEncuestada;
                Encuesta objSesion = new Encuesta();
                string userIdApp;
                userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();
                if (idPregunta == 1)
                {
                    idPregunta = 1;
                }
                else if (padreYorden.el_IdRespuestaPadre != 0)
                {
                    idPregunta = padreYorden.el_IdRespuestaPadre;
                }
                if (flujo == "SIG" || flujo == "TEM")
                {
                    watch = System.Diagnostics.Stopwatch.StartNew();
                    colleccionPreguntas = pregunta.getPreguntaSiguiente(codHogar, idTema, idInstrumento, idPregunta);
                    watch.Stop();
                    elapsedMs = watch.ElapsedMilliseconds;
                    log.Info("metodo getPreguntaSiguiente , tiempoDuracion: " + elapsedMs);
                    var serializePersonas = Newtonsoft.Json.JsonConvert.SerializeObject(colleccionPreguntas);
                    objSesion.guardarCampoSesion(int.Parse(userIdApp), "COLLECIONPERSONAS", serializePersonas);
                    // Elimina la marca de capitulo terminado -- GDV
                    if (flujo == "SIG")
                    {
                        watch = System.Diagnostics.Stopwatch.StartNew();
                        tema.eliminarFinalizarCapitulo(codHogar, idTema, Usuario);
                        watch.Stop();
                        elapsedMs = watch.ElapsedMilliseconds;
                        log.Info("metodo eliminarFinalizarCapitulo , tiempoDuracion: " + elapsedMs);
                        // Actualiza el estado de la encuesta a 'ACTIVA' -- GDV
                        watch = System.Diagnostics.Stopwatch.StartNew();
                        hogar.actualizarEstadoEncuesta(codHogar, usuario, "5");
                        watch.Stop();
                        elapsedMs = watch.ElapsedMilliseconds;
                        log.Info("metodo actualizarEstadoEncuesta , tiempoDuracion: " + elapsedMs);
                    }

IgedEncuesta/Controllers/ReporteEncuestaController.cs
using AdministracionInstrumentos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IgedEncuesta.Controllers
{

    public class ReporteEncuestaController : Controller
    {
        //
        // GET: /ReporteEncuesta/
        ~ReporteEncuestaController()
        {

        }

        public ActionResult ReporteEncuesta()
        {
            string Usuario = string.Empty;
            Usuario = Request.Cookies["SesionIged"]["USUARIO"].ToString();
            gic_Hogar hogar = new gic_Hogar();
            List<gic_ReporteMiembros> lista = new List<gic_ReporteMiembros>();
            lista = hogar.get_reporteMiembrosXcodigo(Usuario);
            ViewBag.EncuestaActiva = encuestaActiva();
            return View(lista);
        }
       

        public FileResult DescargarSoporte(string ruta, string codigoHogar)
        {
            string contentType = "application/pdf";
            return File(ruta, contentType, codigoHogar + ".pdf");
        }

        public string encuestaActiva()
        {
            string codigo =string.Empty;
            gic_Hogar hogar = new gic_Hogar();
            string Usuario = string.Empty;
            Usuario = Request.Cookies["SesionIged"]["USUARIO"].ToString();
            codigo = hogar.encuestaActiva(Usuario);
            return codigo;
        }


    }
}

IgedEncuesta/Views/ReporteEncuesta/ReporteEncuesta.cshtml
@model IEnumerable<AdministracionInstrumentos.gic_ReporteMiembros>

@{

    ViewBag.Title = "Reporte";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";

    var filaGrid = new AdministracionInstrumentos.gic_ReporteMiembros();
    // Instanciamiento del helper webgrid
    var grid = new WebGrid(Model, canPage: true, canSort: true, rowsPerPage: 10,
    selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContent");
    grid.Pager(WebGridPagerModes.NextPrevious);
    //MIEMBROS DEL HOGAR, FECHA DE CREACION, ESTADO, COLILLA

    string encuestaActiva = (string)ViewBag.EncuestaActiva;
}

<style>
    .marcoGrid2 {
        background-color: #905353;
        border: 0px none;
        padding: 2px 2px 2px 2px;
        border-radius: 5px;
        width: 1100px;
    }
</style>

 <div class="centrarDiv"> 
    <table class="marcoFormulario  efecto2 efecto1" style="width: 1010px;margin-top:20px;">
        <tr>
                <td style="margin-top: 5px;">
                    <br />
                    <h5>PERSONAS ENCONTRADAS</h5>
                    <br />
                </td>
        </tr>
        <tr>
            <td class="bordesDiv2 fondo">
                <div id="gridContent" class="marcoGrid2">
                    @grid.GetHtml(
                        tableStyle: "grid-view",
                        headerStyle: "grid-view-header",
                        rowStyle: "grid-view-tr-normal",
                        alternatingRowStyle: "grid-view-tr-alternate",
                        footerStyle: "grid-view-pgr",
                        columns: grid.Columns(
                        grid.Column("Codigo", "CODIGO" , format: (item =>
                        {
                            if (item.estado == "ANULADA" || item.estado == "")
                            {
                                return Html.Raw(item.codigo);
                            }
                            else if (item.estado == "CERRADA")
                            {
                                
                                return Html.Raw("<a id='lnC_" + item.Codigo.ToString() + "'  onclick='encuestaCerrada(this)'   href='#'>" + item.Codigo.ToString() + "</a> ");
                            }
                            
                            else if ((item.estado != "ACTIVA" || item.estado != "APLAZADA") && (item.Codigo != encuestaActiva && encuestaActiva!=""))
                            {
                                return Html.Raw("<a id='lnA_" + item.Codigo.ToString() + "' onclick='encuestaAbierta(this)'    href='#'>" + item.Codigo.ToString() + "</a> ");
                            }
                            else
                            {
                                return Html.Raw(@Html.ActionLink((string)item.codigo, "Encuesta", "Encuesta", new { codigoHogar = item.codigo, tipo = "REPORTE" }, null));
                            }

                        }), canSort: false),
                        grid.Column("miembrosHogar", "MIEMBROS", canSort: false),
                        grid.Column("fechaCreacion", "FCH. CREACION", canSort: false),
                        grid.Column("estado", "ESTADO", canSort: false),
                        grid.Column("Soporte", "SOPORTE", format: (item =>
                        {
                            if (item.colilla == "" || item.colilla == null)
                            {
                                return Html.Raw("Sin Soporte Cargado");
                            }
                            else
                            {
                                return Html.Raw(@Html.ActionLink((string)"Ver Soporte", "DescargarSoporte", "ReporteEncuesta", new { ruta = @item.colilla, codigoHogar = item.codigo }, null));
                            }

                        }), canSort: false)

                    ))
                    
                </div>
            </td>
        </tr>
        <tr>
            <td><label class="etiqueta" style="font-size: 11px">Total Encuestas: </label> @grid.TotalRowCount.ToString()</td>
        </tr>
    </table>
</div>

<div id="generacionInforme" style="display: none">
</div>

<input id="codigoHogActivo" name="codigoHogActivo" type="hidden" value="@encuestaActiva" />

<div id="encuestaCerrada" style="display: none">
    @using (Html.BeginForm("informePdf", "Encuesta", FormMethod.Post, new { id="form"   }))
    {
<input id="codigoHog" name="hogCodigo" type="hidden" value="" />

    <table>
        <tr>
            <td>La encuesta se encuentra '<b>CERRADA</b>'. ¿Desea generar un informe con las preguntas y respuestas diligenciadas?
            </td>
            <td></td>
        </tr>
    </table>

    }
</div>
<div id="encuestaAbierta" style="display: none">

    <table>
        <tr>
            <td>Usted tiene la encuesta <b>
                <label>@encuestaActiva</label></b> activa.
                <br>
                Si desea editar la encuesta <b>
                    <label id="lblCodHogar"></label>
                </b>primero debe finalizar o abandonar la encuesta activa.
                
            </td>
            <td></td>
        </tr>
    </table>


</div>
 <iframe id="iframe" style="display:none;"></iframe>
<script type="text/javascript">
    function encuestaCerrada(objeto) {
         
         $("#encuestaCerrada").dialog('open');
         var idObjeto = $(objeto).attr('id').split('_');
         var cod = idObjeto[1];
         
        $("#codigoHog").val(cod);
        
    }

    function encuestaAbierta(objeto) {
        
        $("#encuestaAbierta").dialog('open');
        var idObjeto = $(objeto).attr('id').split('_');
        var cod = idObjeto[1];
        $("#codigoHog").val(cod);
        var spanCodigo = "#lblCodHogar";
        $(spanCodigo).html($("#codigoHog").val());
    }


    $(document).ready(function () {
        //alert(@encuestaActiva);
        var codHot = "";
        $('.linkCerrada').on('click', function () {
            
            $("#encuestaCerrada").dialog('open');
            var idObjeto = $(this).attr('id').split('_');
            var cod = idObjeto[1];
            codHot = cod;
            $("#codigoHog").val(cod);
        });



        $('.linkActiva').on('click', function () {
            $("#encuestaAbierta").dialog('open');
            var idObjeto = $(this).attr('id').split('_');
            var cod = idObjeto[1];
            $("#codigoHog").val(cod);
            var spanCodigo = "#lblCodHogar";
            $(spanCodigo).html($("#codigoHog").val());

        });


        $("#encuestaAbierta").dialog({
            autoOpen: false,
            resizable: false,
            width: 550,
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: false,
            dialogClass: 'dialog',
            hide: 'explode',
            buttons: {
                "Cancelar": function () {
                    $(this).dialog("close");
                }

            }

        });

        $("#encuestaCerrada").dialog({
            autoOpen: false,
            resizable: false,
            
            width: 550,
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: false,
            dialogClass: 'dialog',
            hide: 'explode',
            buttons: {
                "Cancelar": function () {
                    $(this).dialog("close");
                },
                "Generar": function () {
                    $(this).dialog().find('form').submit();
                    $(this).dialog("close");
                }

            }

        });

    });

    function generacionInforme(pcodHOT) {
        
        //        window.location ='@Url.Action("informePdf", "Encuesta")?hogCodigo=' + pcodHOT;

        //window.location = '@Url.Action("informePdf", "Encuesta")?hogCodigo=' + pcodHOT;
       

    };

</script>