IgedEncuesta/Controllers/CargaMiebroXHogarController.cs
using IgedEncuesta.Models.mdlGenerico;
using System.Collections.Generic;

using System.Web.Mvc;

namespace IgedEncuesta.Controllers
{
    public class CargaMiebroXHogarController : Controller
    {
        //
        // GET: /CargaMiebroXHogar/

        public ActionResult Index()
        {

            return View();
        }


        public ActionResult obtMiembroXHogar(string codHogar)
        {

            if (!codHogar.Equals("") && codHogar != null){
                GIC_REPORTEXHOGAR hogar = new GIC_REPORTEXHOGAR();
                List<GIC_REPORTEXHOGAR> lista = new List<GIC_REPORTEXHOGAR>();
                lista = hogar.getReporteXHogar(codHogar);
                ViewBag.resultado = lista[0].nombre_completo;
                return PartialView("_MiembrosXHogar", lista);
            }

            return View();

        }

        }
}

IgedEncuesta/Controllers/GeneracionPdfsController.cs
using AdministracionInstrumentos;
using gic_ManipuladorPdf;
using IgedEncuesta.Models.mdlConstancia;
using log4net;
using log4net.Config;
using SelectPdf;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Web.Mvc;



namespace IgedEncuesta.Controllers
{
    public class GeneracionPdfsController : Controller
    {

        private static readonly ILog log = LogManager.GetLogger("Web");
        ~GeneracionPdfsController()
        {

        }

        public GeneracionPdfsController()
        {
            XmlConfigurator.Configure();
        }

        int totalRegistros = 10;
        List<string> pathsArchivos = new List<string>();

        public ActionResult GeneracionPdfs()
        {
            cargarCombo();

            return View();
        }


        public void cargarCombo()
        {
            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = "Seleccione..", Value = "" });
            for (int i = 1; i <= totalRegistros; i++)
            {
                li.Add(new SelectListItem { Text = i.ToString(), Value = i.ToString() });
            }
            ViewBag.Opciones = li;

        }

       [HttpGet]
        public ActionResult GeneraciondescargarConstanciaSAAH(string hogcodigo)
        {

            try
            {
                Boolean val = false;
                
                string Usuario = string.Empty;
                string userIdApp;
                userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();
                Usuario = Request.Cookies["SesionIged"]["USUARIO"].ToString();
                int IdUsuario = 0;
                IdUsuario = int.Parse(userIdApp);
                
                man_ArchivoPdf pdf = new man_ArchivoPdf();
                string rutaArchivo = string.Empty;
                string nombreArchivo = string.Empty;                    
                
                    val = pdf.descargarConstanciaSAAHSinFirmar("1", hogcodigo, out rutaArchivo);
                    if (val) {
                        pathsArchivos.Add(rutaArchivo);
                        nombreArchivo = "constancia_"+ hogcodigo + ".pdf";
                    }

                if (val) {
                    Response.ContentType = "application/pdf";
                    Response.AppendHeader(
                      "Content-Disposition",
                      string.Format(
                        "attachment; filename=" + nombreArchivo,
                        Path.GetFileName(pathsArchivos[0])
                      )
                    );
                    pdf.concatenarArchivosPdf(pathsArchivos, Response.OutputStream);
                    borradoArchivos(pathsArchivos);
                }
                
            }
            catch (Exception ex)
            {
                
                log.Error("Generacion / Generacion , Error: " + ex.Message.ToString());
                throw ex;
            }
            
            ViewBag.Mensaje = "";
            return View();

        }

        public ActionResult DescargarArchivoConstanciaSinFirmar(string hogcodigo)
        {
            if (hogcodigo != null)
            {
                string rutaArchivo = string.Empty;
                rutaArchivo = System.Configuration.ConfigurationManager.AppSettings["RutaArchivoConstanciasSinFirmar"];
                string contentType = "application/pdf";
                var path = Path.Combine(rutaArchivo, "ConstanciaSAAH_" + hogcodigo + ".pdf");
                if (!System.IO.File.Exists(path))
                {
                    try
                    {                        
                        ConstanciaSAAH objconstanciasaah = new ConstanciaSAAH();
                        int hogarexiste = objconstanciasaah.FN_GET_HOGAR_CERRAD_CONSTANCIA(hogcodigo);
                        if (hogarexiste > 0)
                        {
                            ConstanciaSAAHE(hogcodigo);
                            DescargarArchivoConstanciaSinFirmar(hogcodigo);
                        }
                        else {
                            ViewBag.Mensaje = "El archivo no existe.";
                            return View("DescargarConstanciaSAAH");
                        }                       
                    }
                    catch (Exception e)
                    {
                        ViewBag.Mensaje = "El archivo no existe.";
                        return View("DescargarConstanciaSAAH");
                    }
                    ViewBag.Mensaje = "";
                    return File(path, contentType, "ConstanciaSAAH_" + hogcodigo + ".pdf");
                }
                ViewBag.Mensaje = "";
                return File(path, contentType, "ConstanciaSAAH_" + hogcodigo + ".pdf");
            }
            else {
                ViewBag.Mensaje = "";
                return View("DescargarConstanciaSAAH");
            }
            
        }


        public ActionResult AsignarEstadoEncuesta(string hogcodigo, string estado)
        {
            try {

                if (hogcodigo != null && !hogcodigo.Equals("") && !estado.Equals("") && !estado.Equals("undefined") && !estado.ToUpper().Equals("UNDEFINED"))
                {
                    string userIdApp;
                    userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();
                    string Usuario = string.Empty;
                    Usuario = Request.Cookies["SesionIged"]["USUARIO"].ToString();
                    try
                    {
                        ConstanciaSAAH objconstanciasaah = new ConstanciaSAAH();
                        int hogarexiste = objconstanciasaah.fn_getCodigoHogar(hogcodigo);
                        if (hogarexiste > 0)
                        {

                          int val =  objconstanciasaah.FN_UPDATE_HOGAR_SAAH(hogcodigo, estado, userIdApp, Usuario);

                            if (val == 10 ) {
                                ViewBag.Mensaje = "Error al actualizar hogar";
                                return View("EditarEstadoEncuestaSAAH");
                            } else if (val == 1 ) {
                                ViewBag.Mensaje = "Código de hogar " + hogcodigo + " ACTUALIZADO exitosamente";
                                return View("EditarEstadoEncuestaSAAH");
                            } else if (val == 0 )
                            {
                                ViewBag.Mensaje = "Código de hogar no existe";
                                return View("EditarEstadoEncuestaSAAH");
                            }

                        }
                        else
                        {
                            ViewBag.Mensaje = "El archivo no existe.";
                            return View("EditarEstadoEncuestaSAAH");
                        }
                    }
                    catch (Exception e)
                    {
                        ViewBag.Mensaje = "El archivo no existe.";
                        return View("EditarEstadoEncuestaSAAH");
                    }

                    ViewBag.Mensaje = "";
                    return View("EditarEstadoEncuestaSAAH");

                }
                else if (hogcodigo.Equals("")) {
                    ViewBag.Mensaje = "Debe ingresar un código de hogar";
                    return View("EditarEstadoEncuestaSAAH");
                }

                else if (estado.Equals("undefined") || estado.ToUpper().Equals("UNDEFINED"))
                {
                    ViewBag.Mensaje = "Debe seleccionar un estado";
                    return View("EditarEstadoEncuestaSAAH");
                }
                else
                {
                    ViewBag.Mensaje = "Debe ingresar un código de hogar";
                    return View("EditarEstadoEncuestaSAAH");
                }

            } catch (Exception e) {
                ViewBag.Mensaje = "Ocurrio una excepcion en la consulta: "+e.Message.ToString();
                return View("EditarEstadoEncuestaSAAH");
            }
            
            

        }

        public ActionResult DescargarArchivoConstanciaFirmada(string hogcodigo) {
            string rutaArchivo = string.Empty;

            rutaArchivo = System.Configuration.ConfigurationManager.AppSettings["RutaArchivoConstanciasFirmadas"]; ;
            string contentType = "application/pdf";
            var path = Path.Combine(rutaArchivo, "ConstanciaSAAH_" + hogcodigo + ".pdf");
            if (!System.IO.File.Exists(path))
            {
                ViewBag.Mensaje = "El archivo no existe.";
                return View("DescargarConstanciaFirmadaSAAH");
            }
            ViewBag.Mensaje = "";
            return File(path, contentType, "ConstanciaSAAH_" + hogcodigo + ".pdf");
        }

        public ActionResult Generacion(string OpcionSeleccionada)
        {

            try
            {
                string codHogar = string.Empty;
                string Usuario = string.Empty;
                string userIdApp;
                userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();
                Usuario = Request.Cookies["SesionIged"]["USUARIO"].ToString();
                int IdUsuario = 0;
                IdUsuario = int.Parse(userIdApp);
                gic_Hogar hogar = new gic_Hogar();
                man_ArchivoPdf pdf = new man_ArchivoPdf();
                string rutaArchivo = string.Empty;
                string nombreArchivo = string.Empty;
                if (Request.Form["btnGenerarCuestionario"] != null)
                {
                    for (int i = 1; i <= int.Parse(OpcionSeleccionada); i++)
                    {
                        codHogar = hogar.generarCodigoFormularioNuevo(Usuario, IdUsuario);                                                

IgedEncuesta/Controllers/GestionSAAHController.cs
using IgedEncuesta.Models.mdlConstancia;
using System;
using System.Web.Mvc;

namespace IgedEncuesta.Controllers
{
    public class GestionSAAHController : Controller
    {
        //
        // GET: /GestionSAAH/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AsignarmeEntrevista()
        {
            return View();
        }

        public ActionResult AsignarmeEncuesta(string hogcodigo, string estado)
        {
            try
            {

                if (hogcodigo != null && !hogcodigo.Equals("") && !estado.Equals("") && !estado.Equals("undefined") && !estado.ToUpper().Equals("UNDEFINED"))
                {
                    string userIdApp;
                    userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();
                    string Usuario = string.Empty;
                    Usuario = Request.Cookies["SesionIged"]["USUARIO"].ToString();
                    try
                    {
                        ConstanciaSAAH objconstanciasaah = new ConstanciaSAAH();
                        int hogarexiste = objconstanciasaah.fn_getCodigoHogar(hogcodigo);
                        if (hogarexiste > 0)
                        {

                            int val = objconstanciasaah.FN_UPDATE_HOGAR_SAAH(hogcodigo, estado, userIdApp, Usuario);

                            if (val == 10)
                            {
                                ViewBag.Mensaje = "Error al actualizar hogar";
                                return View("AsignarmeEntrevista");
                            }
                            else if (val == 1)
                            {
                                ViewBag.Mensaje = "Código de hogar " + hogcodigo + " ACTUALIZADO exitosamente";
                                return View("AsignarmeEntrevista");
                            }
                            else if (val == 0)
                            {
                                ViewBag.Mensaje = "Código de hogar no existe";
                                return View("AsignarmeEntrevista");
                            }

                        }
                        else
                        {
                            ViewBag.Mensaje = "El archivo no existe.";
                            return View("AsignarmeEntrevista");
                        }
                    }
                    catch (Exception e)
                    {
                        ViewBag.Mensaje = "El archivo no existe.";
                        return View("AsignarmeEntrevista");
                    }

                    ViewBag.Mensaje = "";
                    return View("AsignarmeEntrevista");

                }
                else if (hogcodigo.Equals(""))
                {
                    ViewBag.Mensaje = "Debe ingresar un código de hogar";
                    return View("AsignarmeEntrevista");
                }

                else if (estado.Equals("undefined") || estado.ToUpper().Equals("UNDEFINED"))
                {
                    ViewBag.Mensaje = "Debe seleccionar un estado";
                    return View("AsignarmeEntrevista");
                    
                }
                else
                {
                    ViewBag.Mensaje = "Debe ingresar un código de hogar";
                    return View("AsignarmeEntrevista");
                }

            }
            catch (Exception e)
            {
                ViewBag.Mensaje = "Ocurrio una excepcion en la consulta: " + e.Message.ToString();
                return View("AsignarmeEntrevista");
            }



        }

    }
}

IgedEncuesta/Views/GestionSAAH/AsignarmeEntrevista.cshtml
@{
    ViewBag.Title = "EditarEstadoEncuestaSAAH";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
}


@Html.Partial("_DialogPopup")

<br /><br />

<div class="centrarDiv " id="contenedor">
    <table class="marcoFormulario  efecto2 efecto1 " style="margin: auto; width: 1010px; text-transform: uppercase; font-family: 'Roboto'; font-size: 12px;margin-top:20px;">

        <tr>
            <td style="margin-top: 5px;">
                <br />
                <h5>Asignarme Entrevista</h5>
                <br />
            </td>
        </tr>
        <tr>
            <td>
                <div class="fondo " style="text-align:center;margin:0 auto; border: 1px solid #ccc; border-radius: 5px;width: 90%;text-align:center;padding:20px;">
                    <table style="margin:0 auto;">
                        <tr>
                            <td style="text-align: center;font-family: 'Roboto'; font-size: 13px;">
                                Tener encuenta que si tiene entrevistas con estado Activa, no podra asignarse mas hasta que cambie el estado de la entrevista actual.
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <br />
                                <label for="hogcodigo">Código de hogar:</label>
                                <input type="text" id="hogcodigo" name="hogcodigo" style="margin: auto;width:180px" required />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <br />
                                <div id="mensajeError">@ViewBag.Mensaje </div>                                
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <br />
                                <div id="idasignar" style=" display: none">
                                    Seleccionar el circulo para ASIGNARSE la entrevista:<br />
                                    <label><input type="radio" name="estado" id="ASIGNAR" value="ASIGNAR">Asignar</label>
                                </div>

                            </td>
                        </tr>
                        <tr>
                            <td>
                                <br />
                                <input type="button" name="btnBuscarGrupoFamiliar" value="Buscar grupo familiar" id="btnBuscarGrupoFamiliar" style="margin: auto;width:250px" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <br />
                                <input type="button" name="btnIraAsignarmeEntrevista" value="Regresar a Buscar Entrevista" id="btnIraAsignarmeEntrevista" style="margin: auto;width:250px; display: none" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <br />
                                <input type="button" name="btnEditarEstadoEscuesta" value="Asignarme Entrevista" id="btnEditarEstadoEscuesta" style="margin: auto;width:250px; display: none" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <a hidden href="@Url.Action("DescargarArchivoConstanciaFirmada", "GeneracionPdfs", new { hogcodigo = "8HI49" })">
                                    <input type="button" name="btnlimpiarmensaje" id="btnlimpiarmensaje" value="Descargar Constancia firmada" />
                                </a>
                            </td>
                        </tr>


                    </table>
                </div>
                <div id="miembrosxhogar">
                </div>
                <br />
            </td>
        </tr>

    </table>
</div>

<script>



    $('#btnEditarEstadoEscuesta').click(function (e) {
        var p_hogcodigo = $("#hogcodigo").val();        
        var p_estado = $('input:radio[name=estado]:checked').val();        
        $("#mensajeError").html('');
        var p_hogcodigo = $("#hogcodigo").val();
        location.href = '@Url.Action("AsignarmeEncuesta", "GestionSAAH")?hogcodigo=' + p_hogcodigo + '&estado=' + p_estado;

        $('#miembrosxhogar').html('');
                $.ajax(
                    {
                        data: { codHogar: p_hogcodigo},
                        dataType: 'html',
                        url: '@Url.Action("obtMiembroXHogar", "CargaMiebroXHogar")',
                        success: function (result) {                            
                            $('#miembrosxhogar').append(result);
                            $('#miembrosxhogar').show();
                        },
                        error: function (xhr, textStatus, errorThrown) {
                            alert("Código de hogar no existe o ha ocurrido un error al consultar las bases");
                        }
                    })


    });
</script>


<script type="text/javascript">


    $(document).ajaxStop(function () {
        console.log('entro a la funcion loadingoverlay stop');
        $.LoadingOverlay("hide");
        $("#CargandoDatosMaestro").hide();
    });

    $(document).ajaxStart(function () {
        $("#CargandoDatosMaestro").show();
        console.log('entro a la funcion loadingoverlay start');
        var ruta_Cargando2 = '@Url.Content("~/Content/Imagenes/Cargando2.gif")';
        $.LoadingOverlay("show", "image: " + ruta_Cargando2);
    });
    

    $('#btnBuscarGrupoFamiliar').click(function (e) {
        $("#mensajeError").html('');
        var p_hogcodigo = $("#hogcodigo").val();
        $('#miembrosxhogar').html('');
                $.ajax(
                    {
                        data: { codHogar: p_hogcodigo},
                        dataType: 'html',
                        url: '@Url.Action("obtMiembroXHogar", "CargaMiebroXHogar")',
                        success: function (result) {
                            $('#miembrosxhogar').append(result);
                            $('#miembrosxhogar').show();
                            var resultado = document.getElementById("resultado").innerHTML;
                            var mensaje = document.getElementById("mensaje").innerHTML;
                            console.log('ready! ' + resultado);

                            if (resultado == 'ENTREVISTA NO PERTENECE A SAAH') {
                                $('#btnIraAsignarmeEntrevista').css("display", "none");
                                $('#btnEditarEstadoEscuesta').css("display", "none");
                                $('#idasignar').css("display", "none");
                                $('#btnBuscarGrupoFamiliar').css("display", "block");
                            } else {
                                $('#btnIraAsignarmeEntrevista').css("display", "block");
                                
                                document.getElementById("hogcodigo").disabled = true;
                                $('#idasignar').css("display", "block");
                                $('#btnBuscarGrupoFamiliar').css("display", "none");
                            }



                        },
                        error: function (xhr, textStatus, errorThrown) {
                            alert("Código de hogar no existe o ha ocurrido un error al consultar las bases");
                        }
                    })

    });

    $('#btnIraAsignarmeEntrevista').click(function (e) {
        $("#mensajeError").html('');
        var p_hogcodigo = $("#hogcodigo").val();
    $('#miembrosxhogar').html('');
                $.ajax(
                    {
                        data: { codHogar: p_hogcodigo},
                        dataType: 'html',
                        url: '@Url.Action("AsignarmeEntrevista", "GestionSAAH")',
                        success: function (result) {
                            $('#idasignar').css("display", "none");
                            $('#btnIraAsignarmeEntrevista').css("display", "none");
                            $('#btnEditarEstadoEscuesta').css("display", "none");
                            $('#btnBuscarGrupoFamiliar').css("display", "block");
                            document.getElementById("hogcodigo").disabled = false;
                            $("#hogcodigo").val('');

                        },
                        error: function (xhr, textStatus, errorThrown) {
                            alert("Código de hogar no existe o ha ocurrido un error al consultar las bases");
                        }
                    })

    });

    $('#ASIGNAR').click(function (e) {
        $('#btnEditarEstadoEscuesta').css("display", "block");
    });


</script>