IgedEncuesta/Controllers/SesionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ObjetosTipos;
using Autenticacion;

using System.IO;
using IgedEncuesta.Filters;

using IgedEncuesta.Models.mdlGenerico;

using AdministracionInstrumentos;
using log4net;
using log4net.Config;
using IgedEncuesta.Util;

namespace IgedEncuesta.Controllers
{
    public class SesionController : Controller
    {
        ~SesionController()
        {

        }

         private static readonly ILog log = LogManager.GetLogger("Web");
         public SesionController()
        {
            XmlConfigurator.Configure();
        }

        List<string> selectList = new List<string>();

        public ActionResult Inicio(string u, string a, string t, string na, string p)
        {

            List<NivelAcceso> coleccionNivelAcceso = new List<NivelAcceso>();
            NivelAcceso nivelAcceso = new NivelAcceso();
            SesionAplicacion objAplicacion = new SesionAplicacion();
            List<Parametros> param = new List<Parametros>();
            string tokenPortal;
            List<string> permisos = new List<string>();

            List<Token> tokens = new List<Token>();
            Token objToken = new Token();

            //comentar para probar
            Session["UserIdApp"] = ViewBag.UserIdApp = u;
            Session["App"] = ViewBag.App = a;
            Session["TknApp"] = t;
            Session["IdNivelAcceso"] = na;
            Session["IdPortal"] = p;
           //

            ViewBag.CerrarVentana = false;

            //-------------------------
            try
            {
                if (u != null || u != "")
                //   tokens = objToken.consultarTokenAplicacionPadre(Session["UserIdApp"].ToString(), p) ?? new List<Token>();
                    tokens = objToken.consultarTokenAplicacionPadre(u, p) ?? new List<Token>();

                if (tokens.Any(x => x.idAplicacion == a)) // Verifica que ya exista un token para la aplicacion
                {
                    objToken = tokens.Find(x => x.idAplicacion == a);
                    if (t == objToken.token) // SE VALIDA SI EL TOKEN DE LA APLICACION CORRESPONDE AL TOKEN EN LA BD
                    {
                        string MAC = objAplicacion.GetMACAddress();

                        objAplicacion.getActualizarTokenAplicacion(u, a, p, t, MAC, out param);

                        if (param.Find(x => x.Nombre == "p_Salida").Valor == "1") // SE VALIDA SI SE GENERO BIEN UN NUEVO TOKEN DE APLICACION
                        {
                           // Session["TknApp"] = param.Find(x => x.Nombre == "p_TokenGenerado").Valor;
                            TempData["tk"] = param.Find(x => x.Nombre == "p_TokenGenerado").Valor;
                            tokenPortal = tokens.Find(x => x.idAplicacion == p).token;

                            // Crea la cookie de sesion para el módulo IGED
                            var SesionIged = new HttpCookie("SesionIged");
                            SesionIged["UserIdApp"] = u;
                            SesionIged["App"] = a;
                            SesionIged["TknApp"] = param.Find(x => x.Nombre == "p_TokenGenerado").Valor;
                            SesionIged["Fecha"] = String.Format("{0:dd/MM/yyyy HH:mm:ss}", DateTime.Now);
                            SesionIged["IdNivelAcceso"] = na;
                            SesionIged["IdPortal"] = p;


                            ViewBag.CerrarVentana = false;
                            ViewBag.Lista = null;
                            //cargarOpciones();
                            ViewBag.BusquedaMaestro = "SI";

                            param = new List<Parametros>();
                            objAplicacion.nombresCompletosUsuario(u, out param);

                            //Session["NombresUsuario"] = param.Find(x => x.Nombre == "p_Nombres").Valor;
                            //Session["USUARIO"] = param.Find(x => x.Nombre == "p_Usuario").Valor;
                            //Session["NIVELACCESO"] = coleccionNivelAcceso;

                            SesionIged["NombresUsuario"] = param.Find(x => x.Nombre == "p_Nombres").Valor;
                            SesionIged["USUARIO"] = param.Find(x => x.Nombre == "p_Usuario").Valor;

                            coleccionNivelAcceso = nivelAcceso.consultarNivelAcceso(u, a);
                            var serializedData = Newtonsoft.Json.JsonConvert.SerializeObject(coleccionNivelAcceso);
                            SesionIged["NIVELACCESO"] = serializedData;

                            SesionIged.Expires = DateTime.Now.AddHours(8);
                            Response.Cookies.Add(SesionIged);
                            Encuesta objSesion = new Encuesta();
                            //borrado session para el usuario
                            objSesion.eliminarSesionIdUsuario(u);
                            //CAMBIO SESIONES --insercion primera vez
                            string variables = "ID_USUARIO,PERFILES,VALIDAPERFIL,MODELO,MODELOHOGAR,VALINCLUIDO,GRUPOVICTIMA,CODHOGAR,";
                            variables = variables + "TEMASVALIDAR,CAPTERMI,TEMA,IDTEMA,FLUJO,COLLECIONPERSONAS,PREGUNTAACTUAL,LISTADEPARTAMENTOS,";
                            variables = variables + "LISTAMUNICIPIOS,OPCIONESRESPUESTA,LISTAAUTO,TEMAS,PREGUNTAINICIAL,LISTADEPARTAMENTOSDT,LISTADT,LISTAPA,SYSGUID,LISTAMU,MODELOPERSONA";
                            objSesion.insertarVariablesSesion(variables, u);
                            return View("Inicio");
                           // return View("~/Views/Encuesta/ConformacionHogar.cshtml");
                        }
                        else
                            TempData["inv"] = "Token de Sesión para la aplicación invalido.";
                    }
                    else
                        TempData["inv"] = "Token de Sesión para la aplicación invalido.";
                }
                else
                    TempData["inv"] = "Token de Sesión para la aplicación invalido.";

                //-----------

            }
            catch (Exception e)
            {
                TempData["inv"] = e.Message.ToString();
            }

            return View("SesionInvalida");
        }

        [ExpiraSesionFilter]
        public void actualizarCookie()
        {
            SesionAplicacion objSesionAplicacion = new SesionAplicacion();
            ViewBag.CerrarVentana = false;
            ViewBag.tk = "";
            TempData["msg"] = TempData["err"] = "";

            try
            {
                if (Request.Cookies["SesionPortal"] != null)
                {
                    string valor = "", tokenPortal = "", TokenCookie = "";
                    string app = "", userIdApp = "", tknApp = "";

                    tokenPortal = Request.Cookies["SesionPortal"]["Token"].ToString();
                    valor = Request.Cookies["SesionPortal"]["Aplicaciones"].ToString();

                    app = Request.Cookies["SesionIged"]["App"].ToString();
                    userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();
                    tknApp = Request.Cookies["SesionIged"]["TknApp"].ToString();

                    //if (valor.IndexOf("|" + Session["App"].ToString() + "|") != -1) // SE VALIDA SI EXISTE TOKEN EN LA COOKIE PARA LA APLICACION QUE SE VA A CARGAR
                    if (valor.IndexOf("|" + app + "|") != -1) // SE VALIDA SI EXISTE TOKEN EN LA COOKIE PARA LA APLICACION QUE SE VA A CARGAR
                    {
                        ViewBag.tk = Request.Form["tk"];
                        //TokenCookie = objSesionAplicacion.TokenApp(valor, Session["App"].ToString());
                        TokenCookie = objSesionAplicacion.TokenApp(valor, app);
                        if (TokenCookie == Request.Form["tk"]) // SE VALIDA SI EL TOKEN DE LA APLICACION CORRESPONDE AL TOKEN DE LA COOKIE
                        {
                            //Response.Cookies.Add(objSesionAplicacion.actualizarAppCookie(Session["UserIdApp"].ToString(), Session["App"].ToString(), tokenPortal, Session["TknApp"].ToString(), valor));
                            Response.Cookies.Add(objSesionAplicacion.actualizarAppCookie(userIdApp, app, tokenPortal, tknApp, valor));
                        }
                        else
                        {
                            ViewBag.CerrarVentana = true;
                            TempData["msg"] = "No se pudo realizar esta operación debido a que esta sesión no es valida";
                        }
                    }
                    else
                    {
                        ViewBag.CerrarVentana = true;
                        TempData["msg"] = "No se pudo realizar esta operación debido a que esta sesión no es valida";
                    }
                }
                else
                {
                    ViewBag.CerrarVentana = true;
                    TempData["msg"] = "No se pudo realizar esta operación debido a que esta sesión no es valida";
                }
            }
            catch (Exception e)
            {
                TempData["err"] = e.Message.ToString();
            }

        }

        // GET: 
        //[ExpiraSesionFilter]
        public ActionResult CerrarModulo()
        {
            List<Parametros> param = new List<Parametros>();
            SesionAplicacion objSesionAplicacion = new SesionAplicacion();
            TipoDocumento objTipoDoc = new TipoDocumento();
            string userIdApp, app, tknApp;

            //  cargarOpciones();

            app = Request.Cookies["SesionIged"]["App"].ToString();
            userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();
            tknApp = Request.Cookies["SesionIged"]["TknApp"].ToString();

            Encuesta objSesion = new Encuesta();
            objSesion.eliminarSesionIdUsuario(userIdApp);

IgedEncuesta/Views/Shared/Inicio.cshtml
@{
    ViewBag.Title = "Inicio";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
    }



<body>
    @if (ViewBag.CerrarVentana)
    {
        <script type="text/javascript">
            window.close();
        </script>
    }
    else
    {
        <script type="text/javascript">
            window.location.href = '@Url.Action("Inicio", "ConformacionHogar")';
        </script>
    }
</body>

IgedEncuesta/Views/Shared/SesionInvalida.cshtml
@{
    ViewBag.Title = "Sesion Invalida";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Styles.Render("~/Content/themes/Jquery/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_DialogPopup")
    <br /><br /><br /><br /><br /><br /><br />

    <div>
        <img alt="" src="@Url.Content("~/Content/Imagenes/AccesoDenegado.png")"  style="margin:auto 0px"/>
    </div>
    <script type="text/javascript">
        //window.close();
    </script>  
</body>

IgedEncuesta/Views/Shared/_AccesoDenegado.cshtml
@{
    ViewBag.Title = "SesionInvalida";
}

<body>

    <br /><br />
    <div>
        <img alt="" src="@Url.Content("~/Content/Imagenes/AccesoDenegado2.png")"  style="margin:auto 0px"/>
    </div>
    <br /><br />
</body>

IgedEncuesta/Views/Shared/_DialogPopup.cshtml
<div id="dialog-error" style="display: none">
    Se presento un error en la aplicación. <br/>
    Por favor comuniquese con el administrador del sistema. <br/><br/>
    Error: @TempData["err"]
</div>

<div id="dialog-mensaje" style="display: none" >
    @TempData["msg"]
</div>

<div id="dialog-confirm" style="display: none">
    <p>
        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
        ¿Esta seguro de realizar la operación?
    </p>
</div>

<div id="dialog-invalid" style="display: none" >
    @TempData["inv"]
</div>

<div id="dialog-edit" style="display: none">
</div>

<div id="dialog-detail" style="display: none">
</div>
<script type="text/javascript">
    $(document).ready(function () {
       
        $("#dialog-error").dialog({
            autoOpen: false,
            resizable: false,
            height:200,
            width: 700,
            shadow: true,
            title: 'ATENCION',
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: false,
            dialogClass: 'dialog',
            hide: 'explode',
            open: function (event, ui) {
                $(".ui-dialog-titlebar-close").hide();
                $('.ui-widget-overlay').addClass('custom-overlay');
            },
            close: function(event, ui) {
                $('.ui-widget-overlay').removeClass('custom-overlay');
                $('#dialog-error').dialog('close');

                $(this).dialog('destroy').remove();
            },   
            buttons: {
                "OK": function () {
                    $(this).dialog("close");
                }
                //"Cancel": function () {
                //    $(this).dialog("close");
                //}
            }
        });

        $("#dialog-mensaje").dialog({
            autoOpen: false,
            resizable: false,
            height:160,
            width: 330,
            title: 'ATENCION',
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: false,
            dialogClass: 'dialog',
            hide: 'explode',
            open: function (event, ui) {
                $(".ui-dialog-titlebar-close").hide();
                $('.ui-widget-overlay').addClass('custom-overlay');
            },
            close: function (event, ui) {
                $('.ui-widget-overlay').removeClass('custom-overlay');

                $(this).dialog('destroy').remove();
            },
            buttons: {
                "OK": function () {
                    $(this).dialog("close");

                }
                //"Cancel": function () {
                //    $(this).dialog("close");
                //}
            }
        });

        $("#dialog-invalid").dialog({
            autoOpen: false,
            resizable: false,
            height: 150,
            width: 300,
            title: 'ATENCION',
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: false,
            dialogClass: 'dialog',
            hide: 'explode',
            open: function (event, ui) {
                $(".ui-dialog-titlebar-close").hide();
                $('.ui-widget-overlay').addClass('custom-overlay');
            },
            close: function (event, ui) {
                $('.ui-widget-overlay').removeClass('custom-overlay');

                $(this).dialog('destroy').remove();
                window.open('', '_self', '');
                window.close();
            },
            buttons: {
                "OK": function () {

                    $(this).dialog("close");

                }
                //"Cancel": function () {
                //    $(this).dialog("close");
                //}
            }
        });

        var  temporalMensaje;
        temporalMensaje = '@TempData["msg"]'; 
        if (temporalMensaje != "") {
            //  alert(@TempData["msg"]);
            console.log('@TempData["msg"]');
            $("#dialog-mensaje").dialog('open');
        }

        var  temporalError;
        temporalError = '@TempData["err"]'; 
        if (temporalError != "") {
                 //  alert(@TempData["err"]);
            console.log('@TempData["err"]');
            $("#dialog-error").dialog('open');
            }

        var temporalInvalido;
        temporalInvalido = '@TempData["inv"]';
        if (temporalInvalido != "") {
            //  alert(@TempData["err"]);
            $("#dialog-invalid").dialog('open');
        }

        var url = "";

        $("#dialog-edit").dialog({
            title: 'Create User',
            autoOpen: false,
            resizable: false,
            width: 400,
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: true,
            open: function (event, ui) {
                $(".ui-dialog-titlebar-close").hide();
                $(this).load(url);
            }
        });

        $("#dialog-confirm").dialog({
            autoOpen: false,
            resizable: false,
            height: 170,
            width: 350,
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: true,
            open: function (event, ui) {
                $(".ui-dialog-titlebar-close").hide();

            },
            buttons: {
                "OK": function () {
                    $(this).dialog("close");
                    window.location.href = url;
                },
                "Cancel": function () {
                    $(this).dialog("close");
                }
            }
        });

        $("#dialog-detail").dialog({
            title: 'View User',
            autoOpen: false,
            resizable: false,
            width: 400,
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: true,
            open: function (event, ui) {
                $(".ui-dialog-titlebar-close").hide();
                $(this).load(url);
            },
            buttons: {
                "Close": function () {
                    $(this).dialog("close");
                }
            }
        });

        $("#lnkCreate").on("click", function (e) {
            //e.preventDefault(); //use this or return false
            url = $(this).attr('href');
            $("#dialog-edit").dialog('open');

            return false;
        });

        $(".lnkEdit").on("click", function (e) {
            // e.preventDefault(); use this or return false
            url = $(this).attr('href');
            $(".ui-dialog-title").html("Update User");
            $("#dialog-edit").dialog('open');

            return false;
        });

        $(".lnkDelete").on("click", function (e) {
            // e.preventDefault(); use this or return false
            url = $(this).attr('href');
            $("#dialog-confirm").dialog('open');

            return false;
        });

        $(".lnkDetail").on("click", function (e) {
            // e.preventDefault(); use this or return false
            url = $(this).attr('href');
            $("#dialog-detail").dialog('open');

            return false;
        });

        $("#btncancel").on("click", function (e) {
            $("#dialog-edit").dialog("close");
            return false;
        });



    });

</script>

IgedEncuesta/Views/Shared/_FinSesion.cshtml
@Styles.Render("~/Content/css")
@Styles.Render("~/Content/themes/Jquery/css")
@Styles.Render("~/Content/themes/base/css")
@Scripts.Render("~/bundles/jquery")
@*    @Scripts.Render("~/bundles/jqueryval")*@
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/modernizr")

<script type="text/javascript">
    window.alert = function (message) {

        $(document.createElement('div'))
            .attr({ 'class': 'dialog' })
            .html(message)
            .dialog({
                buttons: {
                    "1": { id: 'Ok', text: 'OK', click: function () { $(this).dialog("close"); }, 'class': 'butonAlert' },
                    //OK: function () { $(this).dialog('close'); }, 'class': 'butonAlert'
                },
                close: function () { $(this).remove(); },
                resizable: false,
                height: 150,
                width: 300,
                show: { effect: 'drop', direction: "up" },
                modal: true,
                draggable: false,
                dialogClass: 'dialog butonAlert',
                hide: 'explode'
            });
    };
</script>

<body>
    <script type="text/javascript">
        alert('Su sesión ha finalizado, vuelva a ingresar al módulo desde el Portal de Aplicaciones.');
        window.setInterval('window.close()', 2000);
    </script>
</body>

IgedEncuesta/Views/Shared/_FuentePersona.cshtml
@model IEnumerable<IgedEncuesta.Models.mdlFuente.FuentePersona>

@{
    ViewBag.Title = "MaestroVictimas";
    var lista = (List<string>)TempData["SelectList"];
    

    // TempData["TotalConsulta"] = Model.Count();
    var total = Model.Count();
    TempData["TotalConsulta"] = total;

    TempData["PERFILES"] = Model;
    TempData.Keep("PERFILES");
    List<IgedEncuesta.Models.mdlFuente.FuentePersona> modeloHogar = (List<IgedEncuesta.Models.mdlFuente.FuentePersona>)TempData["ModeloHogar"];
    var modelo = ViewBag.ModeloSerializado;
}


<br />

<input type="hidden" id="totalConsulta" value="@total">
<input type="hidden" id="hdModelo" name="ModeloVictimas" value="@modelo">
<div id="gridContentFuente" class="marcoGrid" style="width: 100%">
    @{
        //var filaGrid = new PortalAplicacionesRNI.Models.gridDatos();
        //var grid = new WebGrid(Model);                         
        // Instanciamiento del helper webgrid
        WebGrid grid = new WebGrid(Model, canPage: true, rowsPerPage: 20, canSort: false,
        selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContentFuente");        

        grid.Pager(WebGridPagerModes.NextPrevious);
        //grid.Pager(WebGridPagerModes.All);
        //grid.Bind(Model, rowCount: Model.Count(), autoSortAndPage: false);
    }

    @grid.GetHtml(
                        //htmlAttributes: new { id = "gridContent" }, // id for ajaxUpdateContainerId parameter
                        //htmlAttributes: new { id = "grid" },
                        //mode: WebGridPagerModes.All,
                        tableStyle: "grid-view",
                        headerStyle: "grid-view-header",
                        rowStyle: "grid-view-tr-normal",
                        alternatingRowStyle: "grid-view-tr-alternate",
                        footerStyle: "grid-view-pgr",
                        columns: grid.Columns(
                        grid.Column("FUENTE", "FUENTE"),
                        grid.Column("TIPO_DOC", "TIPO DOCUMENTO"),
                        grid.Column("NUMERO_DOC", "DOCUMENTO"),
                        grid.Column("ESTADO_CEDULA", "ESTADO CEDULA"),                        
                        grid.Column("NOMBRES_COMPLETOS", "NOMBRES"),
                        grid.Column("PARENTESCO", "PARENTESCO"),
                        grid.Column("GENERO", "GENERO"),
                        grid.Column("FECHA_NACIMIENTO", "FECHA NACIMIENTO"),
                        grid.Column("ESTADO_VALORACION", "ESTADO VALORACION"),
                        grid.Column("NUMERO_FORMULARIO", "NÚMERO FORMULARIO"),
                        grid.Column("CODIGO_DECLARACION", "NÚMERO DECLARACION"),
                        grid.Column("FECHA_HECHO", "FECHA OCURRENCIA HECHO"),
                        grid.Column("HECHO_VICTIMIZANTE", "HECHO"),
                        grid.Column("CODIGO_HOGAR", "ENCUESTA"),
                        grid.Column("ESTADO_ENCUESTA", "ESTADO ENCUESTA"),
                        grid.Column("FECHA_ENCUESTA", "FECHA ENCUESTA"),
                        grid.Column("VIGENCIA_ENCUESTA", "VIGENCIA ENCUESTA")

                       )
    )

</div>

IgedEncuesta/Views/Shared/_LayoutMenu.cshtml
@{
    Layout = null;
    var cookie = Request.Cookies.Get("SesionIged");
    string NOMBRES = cookie["NombresUsuario"].ToString();
}

<!DOCTYPE html>

<html style="background-color: white">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ENTREVISTA DE CARACTERIZACIÓN</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/Jquery/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/general")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/modernizr")
     @Scripts.Render("~/bundles/loading")

    <style>
        .ui-tooltip {
            background: #58ACFA;
            color: white;
            border: none;
            padding: 0;
            opacity: 1;
            width: 100px;
            text-align: center;
            position: absolute;
        }

        .ui-tooltip-content {
            position: relative;
            padding: 1em;
        }

            .ui-tooltip-content::after {
                content: '';
                position: absolute;
                border-style: solid;
                display: block;
                width: 0;
            }

        .right .ui-tooltip-content::after {
            top: 18px;
            left: -10px;
            border-color: transparent #58ACFA;
            border-width: 10px 10px 10px 0;
        }

        .left .ui-tooltip-content::after {
            top: 18px;
            right: -10px;
            border-color: transparent #58ACFA;
            border-width: 10px 0 10px 10px;
        }

        .top .ui-tooltip-content::after {
            bottom: -10px;
            left: 72px;
            border-color: #58ACFA transparent;
            border-width: 10px 10px 0;
        }

        .bottom .ui-tooltip-content::after {
            top: -10px;
            left: 72px;
            border-color: #58ACFA transparent;
            border-width: 0 10px 10px;
        }
    </style>
</head>
<body>
    <div id="wrapper">
        <div id="header">
            <div>
                <img alt="" src="@Url.Content("~/Content/Imagenes/headerRound.png")" height="110" />
            </div>
        </div>
        <div class="barraMenu" style="vertical-align: central;">
            <table style="width: 100%">
                <tr style="vertical-align: central;">
                    <td style="text-align: left; width: 94%; padding-left: 1em; vertical-align: central;">
                        @Html.Label(" BIENVENID@: " + @NOMBRES, new { style = "font: 13px Roboto, Helvetica, Arial, sans-serif; color:#424242; font-weight:600; width:700px; text-transform: uppercase;" })
                    </td>                 
                    <td style="text-align: left; width: 94%; padding-left: 1em; vertical-align: central;">                        
                        @Html.Partial("_VersionAplicacion")
                    </td>
                    <td style="text-align: center; width: 2%;">
                        @* @Html.ActionLink("Cambiar Contraseña", "CambiarContrasenaMenu", "Login", null, new { style = "font: 11px Roboto, Helvetica, Arial, sans-serif; text-decoration:none;" })*@
                        <a href='@Url.Action("DescargarManual", "Sesion")' id="imgDescargarManual" title ="Guía de Usuario">
                            <img src='@Url.Content("~/Content/Icons/GuiaUsuario.png")' style="width:20px" />
                        </a>
                    </td>
                    <td style="text-align: center; width: 2%;">
                        @* @Html.ActionLink("Cambiar Contraseña", "CambiarContrasenaMenu", "Login", null, new { style = "font: 11px Roboto, Helvetica, Arial, sans-serif; text-decoration:none;" })*@
                        <a href=@Url.Action("Inicio", "ConformacionHogar") id="imgVolver" title="Página de Inicio">
                            <img src='@Url.Content("~/Content/Icons/home.png")' style="width:20px" />
                        </a>
                    </td>
                    <td style="text-align: center; width: 3%;">
                        <a href='@Url.Action("CerrarModulo", "Sesion")' title="Cerrar Módulo">
                            <img src='@Url.Content("~/Content/Icons/logout.png")' style="width:20px" />
                        </a>
                    </td>
                </tr>
            </table>
            <div align="center">
                @Html.Partial("_Menu")
            </div>
        </div>

        

        <div id="content">
            <br/>
            <div id="CargandoDatosMaestro" style="display: none;">
                <h5>Procesando por favor espere.....</h5>
                <img alt="" src="@Url.Content("~/Content/Imagenes/Cargando3.gif")" />
            </div>
            @RenderBody()
            <div class="push"></div>
        </div>
        

        <div id="footer">
            <img alt="" src="@Url.Content("~/Content/Imagenes/FooterRound.png")" height="50">
            <h4 class="textoPie">© Copyright 2012 - VIVANTO es una marca de la Unidad para la Atención y Reparación Integral a las Víctimas, desarrollada por la Organización Internacional para las Migraciones (OIM) gracias al apoyo financiero de la Agencia del Gobierno de Estados Unidos para el Desarrollo Internacional (USAID).<br />
                Cualquier copia o adaptación de este Software es ilegal.
Versión 1.0 - Resolución 1024*768 o superior.</h4>
        </div>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

<script type="text/javascript">

    var timeout = '@System.Web.Configuration.WebConfigurationManager.AppSettings["CicloVerificarFinSesion"]';

    $(function () {
        $(document).tooltip({
            position: {
                my: "center top",
                at: "left bottom+10",
                collision: "flipfit flip",
            },
            tooltipClass: "bottom"
        })
    });

    $(document).ready(function () {
        $(".notonbeforeunload").mousedown(function () {
            window.onbeforeunload = null;
        });
    });

    window.alert = function (message) {

        $(document.createElement('div'))
            .attr({ 'class': 'dialog' })
            .html(message)
            .dialog({
                buttons: {
                    "1": { id: 'Ok', text: 'OK', click: function () { $(this).dialog("close"); }, 'class': 'butonAlert' },
                },
                close: function () { $(this).remove(); },
                resizable: false,
                height: 150,
                width: 300,
                show: { effect: 'drop', direction: "up" },
                modal: true,
                draggable: false,
                dialogClass: 'dialog butonAlert',
                hide: 'explode'
            });
    };

    var loop = timeout * 60000;
    setInterval('VerificarFinSesion()', loop);

    function VerificarFinSesion() {
        $.ajax({

            dataType: 'json', //el tipo de dato que nos regresara el servidor en este caso regresa html
            url: '@Url.Action("VerificarFinSesion", "Sesion")',

            success: function (result) { // Variable return contains the data we get from serverside
                if (result == 'cerrada') {
                    alert('Su sesión ha finalizado, vuelva a ingresar al módulo desde el Portal de Aplicaciones.');
                    window.setInterval('window.close()', 2000);
                    //window.close();
                }
            }
        });
    };

</script>

IgedEncuesta/Views/Shared/_VersionAplicacion.cshtml
<div style="width: 100%; border-collapse: separate; border-spacing: 10px;">
    <h3 style="font-weight: normal; font-size:10px; text-transform: uppercase; font-family: 'Roboto';">Versión 3.0</h3>
</div>