IgedEncuesta/Controllers/CargueConstanciaSAAHFirmadaController.cs
using System.Web.Mvc;
using AdministracionInstrumentos;
using log4net;


namespace IgedEncuesta.Controllers
{
    public class CargueConstanciaSAAHFirmadaController : Controller
    {
        private static readonly ILog log = LogManager.GetLogger("Web");
        //
        // GET: /CargueConstanciaSAAHFirmada/
        public ActionResult CargueConstanciaSAAHFirmada()
        {
            return View();
        }
        /*public void cargarConstanciaFirmadaSAAh(string tipopersona)
        {

            Encuesta objSesion = new Encuesta();
            try
            {
                string userIdApp;
                userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();


                gic_adminconfig adminConfig = new gic_adminconfig();
                List<gic_adminconfig> _Config = new List<gic_adminconfig>();
                _Config = adminConfig.GetAdminConfiguracion("path.constanciasfirmadas");
                var httpPostedFile = System.Web.HttpContext.Current.Request.Files["UploadedImageTutor"];
                Guid g = Guid.NewGuid();
                string sguid = g.ToString();
                string nombreArchivo = sguid + ".pdf";
                gic_ArchivoColilla datosSol = new gic_ArchivoColilla();
                HttpCookie reqCookies = Request.Cookies["SesionIged"];
                string usuario = reqCookies["USUARIO"].ToString();
                if (httpPostedFile != null)
                {
                    var fileSavePath = Path.Combine(_Config.First().ADMINCFG_VALUE, nombreArchivo);
                    datosSol.arc_url = fileSavePath;
                    datosSol.usu_UsuarioCreacion = usuario;
                    datosSol.tipopersona = tipopersona;

                    var guid = datosSol.insertaArchivoSoportes(datosSol, sguid);
                    objSesion.guardarCampoSesion(int.Parse(userIdApp), "SYSGUID", guid);

                    string sys = objSesion.getValorCampoSesion("SYSGUID", userIdApp);

                    httpPostedFile.SaveAs(fileSavePath);
                }

            }
            catch (Exception e)
            {
                log.Error("EncuestaController / cargarSoporte , Error: " + e.Message.ToString());
            }


        }*/

        [HttpGet]
        [ActionName("conteoConstanciaFirmada")]
        public JsonResult conteoConstanciaFirmada(string codHogar)
        {
            int codigo = 0;
            gic_Hogar hogar = new gic_Hogar();            
            codigo = hogar.existeConstanciaFirmada(codHogar);
            return Json(codigo, JsonRequestBehavior.AllowGet);
        }


    }
}

IgedEncuesta/Controllers/CargueSoporteController.cs
using AdministracionInstrumentos;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace IgedEncuesta.Controllers
{
    public class CargueSoporteController : Controller
    {
        ~CargueSoporteController()
        {

        }


        public ActionResult CargueSoporte()
        {
            return View();
        }

        [HttpGet]
        [ActionName("idEncuesta")]
        public JsonResult idEncuesta(string codHogar)
        {

            string codigo = string.Empty;
            gic_Hogar hogar = new gic_Hogar();

            codigo = hogar.get_idEncuesta(codHogar);
            return Json(codigo, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [ActionName("conteoSoporte")]
        public JsonResult conteoSoporte(string codHogar)
        {
            int codigo = 0;
            gic_Hogar hogar = new gic_Hogar();
            codigo = hogar.existeColilla(codHogar);
            
            return Json(codigo, JsonRequestBehavior.AllowGet);
        }

        public FileResult DescargarSoporte(string codigoHogar)
        {
            gic_adminconfig adminConfig = new gic_adminconfig();
            List<gic_adminconfig> _Config = new List<gic_adminconfig>();
            _Config = adminConfig.GetAdminConfiguracion("path.colilla");
            string nombreArchivo = codigoHogar + ".pdf";
            string ruta =  Path.Combine(_Config.First().ADMINCFG_VALUE, nombreArchivo);;
            string contentType = "application/pdf";
            return File(ruta, contentType, codigoHogar + ".pdf");
        }
    }
}

IgedEncuesta/Controllers/EncuestaController.cs
using AdministracionInstrumentos;
using iTextSharp.text;
using iTextSharp.text.pdf;
using log4net;
using log4net.Config;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace IgedEncuesta.Controllers
{
    public class EncuestaController : Controller
    {

        private static readonly ILog log = LogManager.GetLogger("Web");
        List<PdfReader> memoriaReaderes = new List<PdfReader>();
        public EncuestaController()
        {
            XmlConfigurator.Configure();
        }

        ~EncuestaController()
        {

        }

        private string Usuario = string.Empty;
        private string codigoEncuesta = string.Empty;
        public ActionResult Encuesta(string codigoHogar = null, string tipo = null)
        {
            try
            {
                Encuesta objSesion = new Encuesta();
                string userIdApp;
                userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();
                gic_Tema tema = new gic_Tema();
                List<gic_Tema> temas = null;

                var perfiles = objSesion.getValorCampoSesion("PERFILES", userIdApp);
                temas = tema.getTemasxInstrumento(1, 1, perfiles);
                var serializedData = Newtonsoft.Json.JsonConvert.SerializeObject(temas);
                objSesion.guardarCampoSesion(int.Parse(userIdApp), "TEMAS", serializedData);
                List<gic_Tema> temasValidar = null;

                /************************************************************************
                PARA QUE NO VALIDE LA SESION , 
                *************************************************************************/
                if (codigoHogar == null)
                    codigoHogar = objSesion.getValorCampoSesion("CODHOGAR", userIdApp);
                else
                    objSesion.guardarCampoSesion(int.Parse(userIdApp), "CODHOGAR", codigoHogar);
                
                codigoEncuesta = codigoHogar;
                temasValidar = tema.getTemasValidados(codigoEncuesta);
                
                var serializeTemas = Newtonsoft.Json.JsonConvert.SerializeObject(temasValidar);
                objSesion.guardarCampoSesion(int.Parse(userIdApp), "TEMASVALIDAR", serializeTemas);
                int terminoCap = tema.get_VerficarCapitulosPrimeros(codigoEncuesta);
                
                objSesion.guardarCampoSesion(int.Parse(userIdApp), "CAPTERMI", terminoCap.ToString());
                //adicion para  guardar los valores en una cookie
                return View(temas);
            }
            catch (Exception e)
            {
                log.Error("EncuestaController / Encuesta , Error: " + e.Message.ToString());
                return null;
            }
        }

        //[ExpiraSesionFilter]
        public ActionResult cargarTema(string idTema)
        {

            try
            {

                Encuesta objSesion = new Encuesta();
                string userIdApp;
                userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();
                List<gic_Tema> temas = new List<gic_Tema>();
                gic_Tema tema = new gic_Tema();
                var objeto = objSesion.getValorCampoSesion("TEMAS", userIdApp);
                temas = Newtonsoft.Json.JsonConvert.DeserializeObject<List<gic_Tema>>(objeto);
                tema = temas.FirstOrDefault(x => x.tem_IdTema == int.Parse(idTema));
                var serializeTema = Newtonsoft.Json.JsonConvert.SerializeObject(tema);
                objSesion.guardarCampoSesion(int.Parse(userIdApp), "TEMA", serializeTema);
                int preguntaInicial = 1;
                objSesion.guardarCampoSesion(int.Parse(userIdApp), "PREGUNTAINICIAL", preguntaInicial.ToString());
                objSesion.guardarCampoSesion(int.Parse(userIdApp), "IDTEMA", idTema.ToString());
                string codigoEncuesta = objSesion.getValorCampoSesion("CODHOGAR", userIdApp);
                int idInstrumento = int.Parse(System.Configuration.ConfigurationManager.AppSettings["IdInstrumento"].ToString());
                gic_PreguntaRespuestasFlujo preguntasRespuestasFlujo = new gic_PreguntaRespuestasFlujo();
                preguntasRespuestasFlujo = PreguntaMostrar(codigoEncuesta, int.Parse(idTema), idInstrumento, preguntaInicial, "TEM");
                preguntasRespuestasFlujo.temaAmostrar = tema;
                return PartialView("_CargaEncuesta", preguntasRespuestasFlujo);
            }
            catch (Exception e)
            {
                log.Error("EncuestaController / cargarTema , Error: " + e.Message.ToString());
                return null;
            }

        }


        //Traer pregunta siguiente
        private gic_PreguntaRespuestasFlujo PreguntaMostrar(string codHogar, int idTema, int idInstrumento, int idPregunta, string flujo)
        {
            try
            {

                gic_PreguntaRespuestasFlujo preguntasRespuestasFlujo = new gic_PreguntaRespuestasFlujo();
                gic_Pregunta pregunta = new gic_Pregunta();
                gic_Tema tema = new gic_Tema();
                gic_Hogar hogar = new gic_Hogar();
                gic_ElementosPadre padreYorden = new gic_ElementosPadre();
                List<gic_PreguntasxPersona> colleccionPreguntas = new List<gic_PreguntasxPersona>();
                List<gic_RespuestaxEncuesta> coleccionRespuestas = new List<gic_RespuestaxEncuesta>();
                gic_RespuestaxEncuesta respuestaXencuesta = new gic_RespuestaxEncuesta();
                gic_PreguntasxPersona preguntaXpersonaGen = new gic_PreguntasxPersona();
                gic_RespuestaxEncuesta respuestaPreguntaGen = new gic_RespuestaxEncuesta();
                DataTable departamentos = new DataTable();
                List<SelectListItem> SelectDepartamentos = new List<SelectListItem>();
                List<gic_RespuestaNuevo> opcionesRespuestas = new List<gic_RespuestaNuevo>();
                gic_RespuestaNuevo objRespuestas = new gic_RespuestaNuevo();
                List<gic_RespuestaNuevo> opcionesRespuestasFiltrado = new List<gic_RespuestaNuevo>();
                DataTable municipios = new DataTable();
                DataTable direccionterritoriales = new DataTable();
                DataTable puntosatencion = new DataTable();
                DataTable municipiosatencion = new DataTable();
                List<SelectListItem> SelectMunicipios = new List<SelectListItem>();
                List<SelectListItem> SelecDireccionesTerritoriales = new List<SelectListItem>();
                List<SelectListItem> SelecPuntosDeAtencion = new List<SelectListItem>();
                List<SelectListItem> SelecMunicipioAtencion = new List<SelectListItem>();

                var watch = System.Diagnostics.Stopwatch.StartNew();
                int idPersonaEncuestada = hogar.get_IdPersonaEncuestada(codHogar);
                watch.Stop();
                var elapsedMs = watch.ElapsedMilliseconds;
                log.Info("metodo get_IdPersonaEncuestada , tiempoDuracion: " + elapsedMs);
                watch = System.Diagnostics.Stopwatch.StartNew();
                padreYorden = pregunta.getMaxPreguntaPadre(codHogar, idTema);
                watch.Stop();
                elapsedMs = watch.ElapsedMilliseconds;
                log.Info("metodo getMaxPreguntaPadre , tiempoDuracion: " + elapsedMs);
                List<string> listaAutoCompletar = new List<string>();
                HttpCookie reqCookies = Request.Cookies["SesionIged"];
                string usuario = reqCookies["USUARIO"].ToString();
                
                preguntasRespuestasFlujo.flujo = flujo;
                preguntasRespuestasFlujo.idPersonaEncuesta = idPersonaEncuestada;
                Encuesta objSesion = new Encuesta();
                string userIdApp;
                userIdApp = Request.Cookies["SesionIged"]["UserIdApp"].ToString();
                if (idPregunta == 1)
                {
                    idPregunta = 1;
                }
                else if (padreYorden.el_IdRespuestaPadre != 0)
                {
                    idPregunta = padreYorden.el_IdRespuestaPadre;
                }
                if (flujo == "SIG" || flujo == "TEM")
                {
                    watch = System.Diagnostics.Stopwatch.StartNew();
                    colleccionPreguntas = pregunta.getPreguntaSiguiente(codHogar, idTema, idInstrumento, idPregunta);
                    watch.Stop();
                    elapsedMs = watch.ElapsedMilliseconds;
                    log.Info("metodo getPreguntaSiguiente , tiempoDuracion: " + elapsedMs);
                    var serializePersonas = Newtonsoft.Json.JsonConvert.SerializeObject(colleccionPreguntas);
                    objSesion.guardarCampoSesion(int.Parse(userIdApp), "COLLECIONPERSONAS", serializePersonas);
                    // Elimina la marca de capitulo terminado -- GDV
                    if (flujo == "SIG")
                    {
                        watch = System.Diagnostics.Stopwatch.StartNew();
                        tema.eliminarFinalizarCapitulo(codHogar, idTema, Usuario);
                        watch.Stop();
                        elapsedMs = watch.ElapsedMilliseconds;
                        log.Info("metodo eliminarFinalizarCapitulo , tiempoDuracion: " + elapsedMs);
                        // Actualiza el estado de la encuesta a 'ACTIVA' -- GDV
                        watch = System.Diagnostics.Stopwatch.StartNew();
                        hogar.actualizarEstadoEncuesta(codHogar, usuario, "5");
                        watch.Stop();
                        elapsedMs = watch.ElapsedMilliseconds;
                        log.Info("metodo actualizarEstadoEncuesta , tiempoDuracion: " + elapsedMs);
                    }

IgedEncuesta/Views/CargueConstanciaSAAHFirmada/CargueConstanciaSAAHFirmada.cshtml
@{
    ViewBag.Title = "CargueConstanciaSAAHFirmada";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
}


@Html.Partial("_DialogPopup")

    <br />
    <div class="centrarDiv " id="contenedor">
        <table class="marcoFormulario  efecto2 efecto1 " style="margin: auto; width: 1010px; text-transform: uppercase; font-family: 'Roboto'; font-size: 12px;margin-top:20px;">
            <tr>
                <td style="margin-top: 5px;">
                    <br />
                    <h5>CARGAR ENCUESTA FIRMADA SAAH</h5>
                    <br />
                </td>
            </tr>
            <tr>
                <td>
                    <div class="fondo " style="text-align:center;margin:0 auto; border: 1px solid #ccc; border-radius: 5px;width: 90%;text-align:center;padding:20px;">
                        <table style="margin:0 auto; ">
                            <tr>
                                <td class="etiqueta" style="font-size: 11px;">Código del Hogar:&nbsp;&nbsp;&nbsp;</td>
                                <td>
                                    @Html.TextBox("CODIGO", "", new { id = "txtCodigo", style = "width:100px;font-size:12px;text-transform:uppercase;font-family:Roboto;", maxlength = "5" })
                                </td>
                            </tr>
                            <tr></tr>
                            <tr>

                                <td colspan="2">
                                    <br />
                                    <input type="button" name="btnCargar" value="Cargar" id="btnCargar" style="margin: auto;width:180px" />
                                </td>
                            </tr>
                        </table>
                    </div>
                    <br />
                </td>
            </tr>
        </table>
    </div>

<input id="idEncuesta" type="hidden" value="" />
<div id="cargarSoporte" style="display: none">
    <table>

        <tr>
            <td>
                <table>
                    <tr>
                        <td>
                            <img src="@Url.Content("~/Content/Caracterizacion/Modal-Alerta.png")" height="50" alt="Cargar soporte" />
                        </td>
                        <td>
                            <label id="lblMensajeSop"></label>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                <table class="tabla1" id="uploadtable">
                    <tr>
                        <td>
                            <input id="fileUpload" type="file" name="fileUpload[0]" accept=".pdf" />
                        </td>
                    </tr>
                </table>
            </td>
            <td></td>
        </tr>
    </table>


</div>

<script type="text/javascript">
    $(document).ready(function () {


        $('#btnCargar').click(function (e) {
            $('#fileUpload').replaceWith($('#fileUpload').clone());
            var conteo;
            if ($("#txtCodigo").val() != "") {
                var codi = obtenerCodHogar();
                
                if ($('#idEncuesta').val() != "") {
                    $("#cargarSoporte").dialog('open');
                    var spanEstado = "#lblMensajeSop";
                    conteo = conteoSoporte();
                    
                    if (conteo == 0) {
                        $(spanEstado).html("Realize el cargue de la constancia.");
                        $("#btnVerSopo").hide();
                    } else {
                        $(spanEstado).html("Usted ya realizo el cargue de la constancia, si desea sobrescribirla, adjunte su archivo a cargar.");
                        $("#btnVerSopo").show();
                    }
                } else {
                    alert("La entrevista no existe en la Base de Datos.");
                }
            } else {
                alert("Digite un codigo de Hogar.");
            }

        });

        $("#cargarSoporte").dialog({
            autoOpen: false,
            resizable: false,
            //height: 400,
            width: 550,
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: false,
            dialogClass: 'dialog',
            hide: 'explode',
            buttons: [{
                text: "Cargar",
                id: "btnCargarCol",
                click: function () {
                    cargarArchivo();
                    $(this).dialog("close");
                }
            }, {
                text: "Cancelar",
                id: "btnCancelarCol",
                click: function () {
                    $(this).dialog("close");
                }
            }, {
                text: "Ver Soporte",
                id: "btnVerSopo",
                click: function () {
                    generacionInforme();
                }
            }]
        });

    });

    var id;
    function obtenerCodHogar() {

        var codigo = "";
        $.ajax({
            type: "GET",
            datatype: "json",
            // traditional: true,
            contentType: "application/json; charset=utf-8",
            url: '@Url.Action("idEncuesta", "CargueSoporte")',
            data: { "codHogar": $("#txtCodigo").val() },
            async: false,
            success: function (result) {
                codigo = result;
                $('#idEncuesta').val("" + result);
            }

        });
        return codigo;
    }

    function conteoSoporte() {

        var codigo = "";
        $.ajax({
            type: "GET",
            datatype: "json",
            contentType: "application/json; charset=utf-8",
            url: '@Url.Action("conteoConstanciaFirmada", "CargueConstanciaSAAHFirmada")',
            data: { "codHogar": $("#txtCodigo").val() },
            async: false,
            success: function (result) {
                codigo = result;

            }
        });

        return parseInt(codigo);
    }


    function cargarArchivo() {

        var data = new FormData();
        var files = $("#fileUpload").get(0).files;
        if (files.length > 0) {
            data.append("UploadedImage", files[0]);

            data.append("codHogar", $("#txtCodigo").val());
            
            var ajaxRequest = $.ajax({
                type: "POST",
                //url: "/api/fileupload/uploadfile",
                //data: { "codHogar": $("#txtCodigo").val() },
                url: '@Url.Action("cargarConstanciaFirmada", "Encuesta")',
                contentType: false,
                processData: false,
                data: data
            });

            ajaxRequest.done(function (xhr, textStatus) {
                // Do other operation
                $("#dialog-cargarSoporte").dialog('close');
                alert("Cargue exitoso de soporte.");
            });

            ajaxRequest.error(function (xhr, textStatus) {
                // Do other operation
                alert("Error en el cargue. Verifique la ruta, donde se almacena el archivo");
            });

        } else {
            alert("Seleccione un archivo.");
        }
    }

    function generacionInforme() {
        //window.location.href = "/GeneracionPdfs/DescargarArchivoConstanciaFirmada" + "?hogcodigo=" + $("#txtCodigo").val();
        location.href = '@Url.Action("DescargarArchivoConstanciaFirmada", "GeneracionPdfs")?hogcodigo=' + $("#txtCodigo").val();
    }




</script>